parameters:
#    desmay_user.example.class: Desmay\UserBundle\Example

services:
#    desmay_user.example:
#        class: %desmay_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
